
# DockerHubで公開中の元イメージを指定
FROM openjdk:11-slim

# インストール可能なパッケージの「一覧」を更新する
RUN apt-get update
# RUN mkdir /usr/src/yamada

# 操作するディレクトリの絶対パス（推奨）を指定します。以降はそのディレクトリを基準にDockerfileに書いた操作が実行されます
WORKDIR /usr/src/


